name: Frontend TS types
run-name: Checking frontend types...
on: [ push ]
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install
        working-directory: frontend

      - name: Type check
        run: pnpm check
        working-directory: frontend
      - run: echo "Frontend / ${{ job.status }}."
